/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrademarksRouteImport } from './routes/trademarks'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const TrademarksRoute = TrademarksRouteImport.update({
  id: '/trademarks',
  path: '/trademarks',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/clients': typeof ClientsRoute
  '/payments': typeof PaymentsRoute
  '/trademarks': typeof TrademarksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/clients': typeof ClientsRoute
  '/payments': typeof PaymentsRoute
  '/trademarks': typeof TrademarksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/clients': typeof ClientsRoute
  '/payments': typeof PaymentsRoute
  '/trademarks': typeof TrademarksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/cases'
    | '/clients'
    | '/payments'
    | '/trademarks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/cases' | '/clients' | '/payments' | '/trademarks'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/cases'
    | '/clients'
    | '/payments'
    | '/trademarks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CasesRoute: typeof CasesRoute
  ClientsRoute: typeof ClientsRoute
  PaymentsRoute: typeof PaymentsRoute
  TrademarksRoute: typeof TrademarksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trademarks': {
      id: '/trademarks'
      path: '/trademarks'
      fullPath: '/trademarks'
      preLoaderRoute: typeof TrademarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CasesRoute: CasesRoute,
  ClientsRoute: ClientsRoute,
  PaymentsRoute: PaymentsRoute,
  TrademarksRoute: TrademarksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
